import Head from 'next/head'




export default function About() {
  return (
    <>
      <Head>
        <title>Axxela 2023 Sustainability Report</title>
        <meta name="description" content="Generated by create next app" /> 
      </Head>
      <main>
        Hello World
        
      </main>
    </>
  )
}