import AnimatedIntro from '@/components/AnimatedIntro'
import Head from 'next/head'




export default function Home() {
  return (
    <>
      <Head>
        <title>Axxela 2023 Sustainability Report</title>
        <meta name="description" content="Generated by create next app" /> 
      </Head>
      <main>
        <AnimatedIntro />
        
      </main>
    </>
  )
}
